"""add cover and author to favorites

Revision ID: ded4015cf428
Revises: 160ecfdd4c01
Create Date: 2026-05-15 15:32:58.007771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded4015cf428'
down_revision = '160ecfdd4c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('author')
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
